# Generated by Django 2.1.7 on 2019-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('ctime', models.CharField(max_length=20)),
                ('locationLat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('locationLng', models.DecimalField(decimal_places=10, max_digits=10)),
                ('imageUrl', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('dtime', models.CharField(max_length=20)),
                ('locationLat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('locationLng', models.DecimalField(decimal_places=10, max_digits=10)),
                ('remark', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portraitRes', models.CharField(max_length=200)),
                ('pubTime', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=20)),
                ('locationLat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('locationLng', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('pasword', models.CharField(max_length=20)),
                ('iden', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=20)),
            ],
        ),
    ]
