# Generated by Django 2.1.7 on 2019-04-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_communicate_delegate_notif_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicate',
            name='ctime',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='communicate',
            name='locationLat',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='communicate',
            name='locationLng',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='locationLat',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='locationLng',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='notif',
            name='locationLat',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='notif',
            name='locationLng',
            field=models.CharField(max_length=12),
        ),
    ]
