# Generated by Django 2.1.7 on 2019-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20190406_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicate',
            name='zan',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delegate',
            name='remark',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
