# Generated by Django 2.1.7 on 2019-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20190406_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('people', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='communicate',
            name='locationLat',
        ),
        migrations.RemoveField(
            model_name='communicate',
            name='locationLng',
        ),
        migrations.AddField(
            model_name='communicate',
            name='Location',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegate',
            name='location',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicate',
            name='ctime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='remark',
            field=models.CharField(max_length=300),
        ),
    ]
